name: Build, Test, and Upload

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # os: [ubuntu-latest] #  macos-14, windows-latest
        os: [macos-14] #  macos-14, windows-latest

    if: ${{ startsWith(github.ref, 'refs/tags') || !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - uses: actions/checkout@v4

    - name: Python - set up ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.21.3
      with:
        output-dir: wheelhouse

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl

  publish:
    name: Publish wheels on ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #  macos-14, windows-latest
        python-version: ["3.11"]
    permissions:
      contents: write
    # OS not important here
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Artifact - download
      uses: actions/download-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: ${{ github.workspace }}
    - name: Artifact - Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/*.whl